# Form implementation generated from reading ui file 'ui\overlay.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Overlay(QtWidgets.QWidget):  # Héritez de QWidget
    closed = QtCore.pyqtSignal()  # Un nouveau signal pour être émis lorsque l'overlay est fermé

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(152, 146)
        Form.setWindowOpacity(0.5)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui\\../../Projet whisper/icons/record.png"))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

    def closeEvent(self, event):
        self.closed.emit()  # Émettez le signal lorsque l'overlay est fermé
        super().closeEvent(event)
        