# Form implementation generated from reading ui file 'ui\src\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 585)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_4.setSpacing(15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_5.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.record_vocal_command = QtWidgets.QToolButton(parent=self.centralwidget)
        self.record_vocal_command.setObjectName("record_vocal_command")
        self.gridLayout_5.addWidget(self.record_vocal_command, 1, 0, 1, 1)
        self.record_note = QtWidgets.QToolButton(parent=self.centralwidget)
        self.record_note.setObjectName("record_note")
        self.gridLayout_5.addWidget(self.record_note, 0, 0, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionadd_project = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\src\\../../icons/folder--plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionadd_project.setIcon(icon)
        self.actionadd_project.setObjectName("actionadd_project")
        self.actionadd_category = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\src\\../../icons/categories.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionadd_category.setIcon(icon1)
        self.actionadd_category.setObjectName("actionadd_category")
        self.actionnew_record = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\src\\../../icons/cassette--plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionnew_record.setIcon(icon2)
        self.actionnew_record.setObjectName("actionnew_record")
        self.actionextract = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui\\src\\../../icons/folder-export.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionextract.setIcon(icon3)
        self.actionextract.setObjectName("actionextract")
        self.actionsetting = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui\\src\\../../icons/gear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionsetting.setIcon(icon4)
        self.actionsetting.setObjectName("actionsetting")
        self.toolBar.addAction(self.actionadd_project)
        self.toolBar.addAction(self.actionadd_category)
        self.toolBar.addAction(self.actionextract)
        self.toolBar.addAction(self.actionnew_record)
        self.toolBar.addAction(self.actionsetting)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.record_vocal_command.setText(_translate("MainWindow", "Vocal command"))
        self.record_note.setText(_translate("MainWindow", "Record note"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionadd_project.setText(_translate("MainWindow", "add_project"))
        self.actionadd_project.setToolTip(_translate("MainWindow", "Add Project"))
        self.actionadd_category.setText(_translate("MainWindow", "add_category"))
        self.actionadd_category.setToolTip(_translate("MainWindow", "Add Category"))
        self.actionnew_record.setText(_translate("MainWindow", "new_record"))
        self.actionnew_record.setToolTip(_translate("MainWindow", "New Record"))
        self.actionnew_record.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionextract.setText(_translate("MainWindow", "extract"))
        self.actionextract.setToolTip(_translate("MainWindow", "Extract"))
        self.actionsetting.setText(_translate("MainWindow", "setting"))
        self.actionsetting.setToolTip(_translate("MainWindow", "Setting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
